### ISSUE TITLE
Installing package from github throws error

### ISSUE THREAD

**Issue by ianhussey** [lhdjung/scrutiny#2]
I've encountered an installation error I haven't seen before.

```{r}
remotes::install_github("lhdjung/scrutiny")
```
returns:
```
Error: Failed to install 'unknown package' from GitHub:
 HTTP error 404.
 No commit found for the ref master

 Did you spell the repo owner (`lhdjung`) and repo name (`scrutiny`) correctly?
 - If spelling is correct, check that you have the required permissions to access the repo.
```

Code taken from readme.rmd and checked against the github repo name, so I'm not sure what's happening. I've tried ```devtools::install_github("lhdjung/scrutiny")``` instead of ```remotes::install_github("lhdjung/scrutiny")``` and same issue. I've checked that I can install other packages with the same command (e.g., ```devtools::install_packages("tidyverse/dplyr")``` ).

**Comment by lhdjung** [comment]
This [might have to do](https://github.com/ropensci/targets/issues/206) with the version of remotes or devtools you have installed. You said that `devtools::install_packages()` works with other packages. Is that also true for `devtools::install_github()`?

If updating is not an option, try `remotes::install_github("lhdjung/scrutiny@main")`.

**Comment by ianhussey** [comment]
Took my sweet time upgrading my R version, but now that I have this works properly.

**Comment by lhdjung** [comment]
Glad to hear! New version coming soon...
