### ISSUE TITLE
`round_up_from()` fails due to numerical precision issue

### ISSUE THREAD

**Issue by kaz462** [lhdjung/scrutiny#43]
Hi @lhdjung , thanks for creating this package! 

The following examples have the same issue as mentioned on [stackoverflow](https://stackoverflow.com/questions/12688717/round-up-from-5#comment110611119_12688836)
```r
> round_up_from(2436.845, 2, 5)
[1] 2436.84
> round_up(2436.845, 2)
[1] 2436.84
```

**Comment by lhdjung** [comment]
Hi @kaz462 , thank you for pointing this out!

I have fixed the bug, and the new version should be on CRAN by next month. (CRAN will be closed for submissions until August 8). To install the corrected version right now, please run:
```
remotes::install_github("lhdjung/scrutiny")
```

New, correct behavior:
``` r
library(scrutiny)
round_up_from(2436.845, 2, 5)
#> [1] 2436.85
round_up(2436.845, 2)
#> [1] 2436.85

packageVersion("scrutiny")
#> [1] '0.2.4.9000'
```

<sup>Created on 2023-07-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
